example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import export_to_xml
from wishlist.views import export_to_json
from wishlist.views import export_xml_id
from wishlist.views import export_json_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import add_barang
from wishlist.views import show_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', export_to_xml, name = 'export_to_xml'),
    path('json/', export_to_json, name = 'export_to_json'),
    path('xml/<int:id>', export_xml_id, name= 'export_xml_id'),
    path('json/<int:id>', export_json_id, name= 'export_json_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='view_ajax'),
    path('ajax/submit/', add_barang, name='add_barang'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from statistics import mode
from django import forms
from wishlist.models import BarangWishlist

class AddBarangForm(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields = "__all__"

        widgets = {
            'name' : forms.TextInput(attrs={'type' : 'text', 'class' : 'form-control'}),
            'price' : forms.TextInput(attrs={'type' : 'text', 'class' : 'form-control'}),
            'description' : forms.Textarea(attrs={'type' : 'textarea', 'class' : 'form-control'})
        }

        name = forms.CharField(label = 'Name', required = True, widget = widgets['name'])
        price = forms.CharField(label = 'Price', required = True, widget = widgets['price'])
        description = forms.CharField(label = 'Description', required = True, widget = widgets['description'])

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from binascii import rledecode_hqx
from tkinter import S
from urllib import response
from django.shortcuts import render
from django.shortcuts import redirect
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import AddBarangForm

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Divany',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Divany',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def export_to_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type = "application/xml")

def export_to_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

def export_xml_id(request, id):
    data = BarangWishlist.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("xml", data), content_type = "application/xml")

def export_json_id(request, id):
    data = BarangWishlist.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('wishlist:show_wishlist'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(rledecode_hqx, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def add_barang(request):
    submitted = False
    if(request.POST):
        form = AddBarangForm(request.POST)
        if (form.is_valid()):
            barang = form.save(commit=False)
            barang.user = request.user
            barang.save()
            response = redirect('wishlist:show_wishlist_ajax')
            return response
        else:
            form = AddBarangForm
            if 'submitted' in request.GET:
                submitted = True
    return render(request, 'wishlist_ajax.html')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<head>
    <meta charset="utf-8">
    <meta name = "viewport" content="width=device-width, inital-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<nav class = "navbar navbar-dark bg-dark">
    <div class = "container-fluid">
        <a class = "navbar-brand mb-0 h1" href="#">{{nama}}</a>
        <div class = "d-flex">
            <button class="btn btn-outline-light"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
        </div>
    </div>
</nav>
<!-- <h5>Nama: </h5>
<p>{{nama}}</p> -->

<table class = "table table-bordered table-hover">
    <tr>
    <thead class = "table-light">
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
    </thead>
    
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h6>Sesi terakhir login: 
    <small class="text-muted">{{last_login }}</small></h5>
<!-- <button><a href="{% url 'wishlist:logout' %}">Logout</a></button> -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, inital-scale=1">
    <title>Wishlist</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>

    </script>
</head>

<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand mb-0 h1" href="#">{{nama}}</a>
        <div class="d-flex">
            <button class="btn btn-outline-light"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
        </div>
    </div>
</nav>
<!-- <h5>Nama: </h5>
<p>{{nama}}</p> -->

<div class = "container-sm position-relative" style="max-width: 50rem; margin: 1rem;">
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="formNama" class="form-label">Nama Barang: </label>
            <input type="text" class="form-control" id="formNama" name="name" placeholder="Barang">
        </div>
        <div class="mb-3">
            <label for="formPrice" class="form-label">Harga Barang: </label>
            <input class="form-control" id="formPrice" rows="3" name="price" placeholder="Description"></input>
        </div>
        <div class="mb-3">
            <label for="formDesc" class="form-label">Deskripsi</label>
            <textarea class="form-control" id="formDesc" rows="2" name="description"
                placeholder="Description"></textarea>
        </div>
        <input class="btn btn-dark" type="submit" value="Add Barang" id="add_barang_button">
        <!-- <button class="btn btn-danger"><a href="{% url 'wishlist:add_barang' %}"
                style="text-decoration: none; color: white;">Back</a></button> -->
    </form>
</div>


<table class="table table-bordered table-hover" id = "table-barang">
    <tr>
        <thead class="table-light">
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
        </thead>

    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    <!-- {% for barang in list_barang %}
    <tr>
        <th>{{barang.nama_barang}}</th>
        <th>{{barang.harga_barang}}</th>
        <th>{{barang.deskripsi}}</th>
    </tr>
    {% endfor %} -->
</table>
<h6>Sesi terakhir login:
    <small class="text-muted">{{last_login }}</small></h5>
    <!-- <button><a href="{% url 'wishlist:logout' %}">Logout</a></button> -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous">

        $.ajax({
            url: "initial_wishlist_data.json",
            type: 'get',
            dataType: 'json',
            error: function(data){
                console.log('Error');
            },
            success: function(data){
                console.log(data);
                // var html_to_append = '';
                // $.each(data, function(i, item){
                //     html_to_append += '<tr>' + '<th>' + item.nama_barang + '</th>' + 
                //     '<th>' + item.harga_barang + '</th>' +
                //     '<th>' + item.deskripsi + '</th>' + '</tr>';
                // });
                // $('#table-barang').html(html_to_append);
            }
        });

        $('#add_barang_button').click(function(event){

        })
    </script>

{% endblock content %}